### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by perkjelsvik** [PerKjelsvik/TTK4115-LinSys#1]
These are tasks/issues we need to do in MatLab/Simulink in order to complete the project. I will not include todos for our lab rapport etc. as they are separate from our code and for a different part of the evaluation. 
- [ ] ~~Plot part 1, finding **V_s**, 5.1.4~~
- [ ] ~~**Step-input** on **x** and **y** for _different controllers_ in the project to make better plots~~
- [x] **Tuning** with new **zeta** and **Omega_0** for the first part of the project. Test if it works.
- [x] Plot part 2, for _each_ controller. Use step-function
- [x] Fix explanation for K_rp, K_pp, K_pd and Omega_0 in latex
- [x] **Code clean-up**. Make it more readable and easy to understand 
- [x] **Tune LQR** _without_ **integral effect**. So far tuned with wrong model implementation
- [x] **Tune LQR** _with_ **integral effect**.
- [x] **Implement Observer** correctly
- [x] **Tune K-matrix** for _Observer_, so far not tuned at all

Final changes, LaTeX
- [x] Line 76, part I. "Summarized, the system can be..."
- [ ] ~~Add simulink-screenshot of Elevation-adjustment in 1.4?~~
- [ ] ~~Simulink and Plot for V_S Part 1.4?~~
- [ ] ~~Step-plot for Part 2?~~
- [x] Matlab-code for placing Observer poles
- [x] Move "Simulink-model after PART IV" to last paragraph
- [x] Problem 4.3 "travel is differentiated three times.." integrated? Therefore more noise, no?
